---
test_name: User Tests
includes:
  - !include common.yaml

stages:
  - name: Create a User
    request:
      method: POST
      url: "{host}/users"
      json:
        id: 1
        name: "Super Man"
        secret_name: "Clark Kent"
        age: 27
        team_id: 1
    response:
      status_code: 200
      json: {}
  
  - name: Get a User
    request:
      method: GET 
      url: "{host}/users/1"
    response:
      status_code: 200
      json: []
  
  - name: Get a User - Not Found
    request:
      method: GET 
      url: "{host}/users/99"
    response:
      status_code: 404
      json: 
        detail: "User not found with id: 99"
  
  - name: Get a User
    request:
      method: GET 
      url: "{host}/users"
      params:
        offset: 0
        limit: 100
    response:
      status_code: 200
      json: []
  
  - name: Update a User
    request:
      method: PATCH 
      url: "{host}/users/1"
      json:
        name: "Super Man"
        secret_name: "Clark Kent"
        age: 28
        team_id: 1
    response:
      status_code: 200
      json:
        id: 1
        name: "Super Man"
        secret_name: "Clark Kent"
        age: 28
        team_id: 1

  - name: Delete a User
    request:
      method: DELETE 
      url: "{host}/users/1"
    response:
      json:
        ok: true
